#!/bin/sh
# Install extlinux on the currently active root device
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

set -e

export BOOT_PARTITION=`cat /proc/mounts | tr -s " " | grep /boot | cut -d " " -f 1 | sed "s, ,,g"`
export DEVICE=`echo ${BOOT_PARTITION} | sed -rn "s,(.+)([0-9]),\1,p"`
export PARTITION=`echo ${BOOT_PARTITION} | sed -rn "s,(.+)([0-9]),\2,p"`

if test -z "${DEVICE}"; then echo "Failed to determine device"; exit 1; fi

dd if=/usr/lib/syslinux/mbr.bin of=${DEVICE}
/usr/sbin/extlinux --install /boot/
systemctl --force poweroff
